---
output:
  pdf_document: default
  html_document: default
---
# Analyse

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
#------------------------------
# Ouvrir données
#------------------------------
setwd("~/Desktop/Credits_recherche/CR_anoure")
anoure <- read.csv('donnees/anoure_nett.csv', header = T)
library(unmarked)
library(AICcmodavg)

#Données réponse
licat_21_1h <- read.csv('donnees/licat_21_1h.csv', header = T)
licat_22_1h <- read.csv('donnees/licat_21_1h.csv', header = T)
lisyl_22_21h <- read.csv('donnees/lisyl_22_21h.csv', header = T)

#Données occupation
MH <- read.csv("donnees/MH_nett.csv", header = T)
route <- read.csv("donnees/routes_nett.csv", header = T)
territoire <- read.csv("donnees/utilisation_territoire_nett.csv", header = T)

#Données détection
#qualite_2021_15h <- read.csv('donnees/qualite_2021_15h.csv', header = T)
#qualite_2021_21h <- read.csv('donnees/qualite_2021_21h.csv', header = T)
qualite_2021_1h <- read.csv('donnees/qualite_2021_1h.csv', header = T)
#qualite_2022_15h <- read.csv('donnees/qualite_2022_15h.csv', header = T)
qualite_2022_21h <- read.csv('donnees/qualite_2022_21h.csv', header = T)
qualite_2022_1h <- read.csv('donnees/qualite_2022_1h.csv', header = T)

#disturb_2021_15h <- read.csv('donnees/disturb_2021_15h.csv', header = T)
#disturb_2021_21h <- read.csv('donnees/disturb_2021_21h.csv', header = T)
disturb_2021_1h <- read.csv('donnees/disturb_2021_1h.csv', header = T)
#disturb_2022_15h <- read.csv('donnees/disturb_2022_15h.csv', header = T)
disturb_2022_21h <- read.csv('donnees/disturb_2022_21h.csv', header = T)
disturb_2022_1h <- read.csv('donnees/disturb_2022_1h.csv', header = T)

jj_21_1h <- read.csv('donnees/JJ_21_1h.csv', header =T)
jj_22_1h <- read.csv('donnees/JJ_22_1h.csv', header =T)
jj_22_21h <- read.csv('donnees/JJ_22_21h.csv', header =T)

```
 
## Corrélation des variables

### Variable de détection
```{r, }
cor(anoure$RecordingQuality, anoure$DisturbanceType)
detection_anoure <- subset(anoure, select = c(RecordingQuality, DisturbanceType))
plot(detection_anoure)
```

### Variable d'occupation

```{r}
occupation_anoure <- merge(MH, route, by ="Enregistre")
occ_anoure <- merge(occupation_anoure, territoire, by = "Enregistre")
occ_anoure$Eau <- occ_anoure$Eau.peu.profonde + occ_anoure$Marais + occ_anoure$Riviere
occ_anoure$Humide <- occ_anoure$Marecage + occ_anoure$Milieu.humide + occ_anoure$Tourbiere
occ_anoure <- subset(occ_anoure, select = c(Enregistre, Total, Agriculture, Eau, Humide)) 

plot(occ_anoure)
```

# Analyse

### LISYL 2022 1h
```{r}
lisyl_22_21h <- subset(lisyl_22_21h, select = -c(Site))
disturb_2022_21h <- subset(disturb_2022_21h, select = -c(Site))
qualite_2022_21h <- subset(qualite_2022_21h, select = -c(Site))
```

Création données unmarked
```{r}
lisyl_22_21h.data <- unmarkedFrameOccu(y = lisyl_22_21h, siteCovs = occ_anoure, obsCovs = list(disturbance = disturb_2022_21h, qualite = qualite_2022_21h))
summary(lisyl_22_21h.data)
```

Modèles
```{r}
#Détectabilité et occupation constante
m00 <- occu(~ 1 ~ 1, data = lisyl_22_21h.data)

##Détectabilité varie, mais occupation est constante
mDetection2 <- occu(~ disturbance + qualite ~ 1, data = lisyl_22_21h.data)
mDetection2

##Détectabilité varie et l'occupation varie
mHumide2 <- occu(~ disturbance + qualite ~ Humide, data = lisyl_22_21h.data)
##Détectabilité constante et l'occupation varie
mHumide3 <- occu(~ 1 ~ Humide, data = lisyl_22_21h.data)

##Détectabilité varie et l'occupation varie
mEaulibre2 <- occu(~ disturbance + qualite ~ Eau, data = lisyl_22_21h.data)
##Détectabilité constante et l'occupation varie
mEaulibre3 <- occu(~ 1 ~ Eau, data = lisyl_22_21h.data)

##Détectabilité varie et l'occupation varie
mAgriculture2 <- occu(~ disturbance + qualite ~ Agriculture, data = lisyl_22_21h.data)
##Détectabilité constante et l'occupation varie
mAgriculture3 <- occu(~ 1 ~ Agriculture, data = lisyl_22_21h.data)

##Détectabilité varie et l'occupation varie !!!
mRoute2 <- occu(~ disturbance + qualite ~ Total, data = lisyl_22_21h.data)
mRoute2
##Détectabilité constante et l'occupation varie
mRoute3 <- occu(~ 1 ~ Total, data = lisyl_22_21h.data)

##Détectabilité varie et l'occupation varie
mAgri_Route2 <- occu(~ disturbance + qualite ~ Agriculture + Total, data = lisyl_22_21h.data)
##Détectabilité constante et l'occupation varie
mAgri_Route3 <- occu(~ 1 ~ Agriculture + Total, data = lisyl_22_21h.data)

```

```{r}
Cands <- list(m00, mDetection2, mHumide2, mEaulibre2, mRoute2, mAgriculture2)
##assign meaningful names to each model 
Model.names <- c("nulle", "psi(.)p(Qualité + Perturbation)","psi(Milieux humides)p(Qualité + Perturbation)", "psi(Eau libre)p(Qualité + Perturbation)", "psi(Route)p(Qualité + Perturbation)", "psi(Agriculture)p(Qualité + Perturbation)") 
##do model selection based on AICc 
aictab(cand.set = Cands,  modnames = Model.names)
```

### LICAT 2021 1h


```{r}
licat_21_1h <- subset(licat_21_1h, select = -c(Site))
disturb_2021_1h <- subset(disturb_2021_1h, select = -c(Site))
qualite_2021_1h <- subset(qualite_2021_1h, select = -c(Site))
```

Création données unmarked
```{r}
licat_21_1h.data <- unmarkedFrameOccu(y = licat_21_1h, siteCovs = occ_anoure, obsCovs = list(disturbance = disturb_2021_1h, qualite = qualite_2021_1h))
summary(licat_21_1h.data)
```

Modèles
```{r, include=FALSE}
#Détectabilité et occupation constante
m0 <- occu(~ 1 ~ 1, data = licat_21_1h.data)

##Détectabilité varie, mais occupation est constante
mDetection <- occu(~ disturbance + qualite ~ 1, data = licat_21_1h.data)

##Détectabilité varie et l'occupation varie
mHumide <- occu(~ disturbance + qualite ~ Humide, data = licat_21_1h.data)
##Détectabilité constante et l'occupation varie
mHumide1 <- occu(~ 1 ~ Humide, data = licat_21_1h.data)


##Détectabilité varie et l'occupation varie
mEaulibre <- occu(~ disturbance + qualite ~ Eau, data = licat_21_1h.data)
##Détectabilité constante et l'occupation varie
mEaulibre1 <- occu(~ 1 ~ Eau, data = licat_21_1h.data)

##Détectabilité varie et l'occupation varie
mAgriculture <- occu(~ disturbance + qualite ~ Agriculture, data = licat_21_1h.data)
##Détectabilité constante et l'occupation varie
mAgriculture1 <- occu(~ 1 ~ Agriculture, data = licat_21_1h.data)

##Détectabilité varie et l'occupation varie
mRoute <- occu(~ disturbance + qualite ~ Total, data = licat_21_1h.data)

##Détectabilité constante et l'occupation varie
mRoute1 <- occu(~ 1 ~ Total, data = licat_21_1h.data)

##Détectabilité varie et l'occupation varie
mAgri_Route <- occu(~ disturbance + qualite ~ Agriculture + Total, data = licat_21_1h.data)
##Détectabilité constante et l'occupation varie
mAgri_Route1 <- occu(~ 1 ~ Agriculture + Total, data = licat_21_1h.data)
```

```{r}
mDetection
mRoute
```

```{r}
Cands <- list(m0, mDetection, mHumide, mEaulibre, mRoute, mAgriculture)
##assign meaningful names to each model 
Model.names <- c("nulle", "psi(.)p(Qualité + Perturbation)","psi(Milieux humides)p(Qualité + Perturbation)", "psi(Eau libre)p(Qualité + Perturbation)", "psi(Route)p(Qualité + Perturbation)", "psi(Agriculture)p(Qualité + Perturbation)") 
##do model selection based on AICc 
aictab(cand.set = Cands,  modnames = Model.names)
```
